var model =
{
    names: ['lille', 'ring', 'midt', 'peke', ['tommel', 'store']],
    fingersAndToes: [
        { side: 'venstre', index: 0, type: 'finger' },
        { side: 'venstre', index: 1, type: 'finger' },
        { side: 'venstre', index: 2, type: 'finger' },
        { side: 'venstre', index: 3, type: 'finger' },
        { side: 'venstre', index: 4, type: 'finger' },
        { side: 'høyre', index: 0, type: 'finger' },
        { side: 'høyre', index: 1, type: 'finger' },
        { side: 'høyre', index: 2, type: 'finger' },
        { side: 'høyre', index: 3, type: 'finger' },
        { side: 'høyre', index: 4, type: 'finger' },
        { side: 'venstre', index: 0, type: 'tå' },
        { side: 'venstre', index: 1, type: 'tå' },
        { side: 'venstre', index: 2, type: 'tå' },
        { side: 'venstre', index: 3, type: 'tå' },
        { side: 'venstre', index: 4, type: 'tå' },
        { side: 'høyre', index: 0, type: 'tå' },
        { side: 'høyre', index: 1, type: 'tå' },
        { side: 'høyre', index: 2, type: 'tå' },
        { side: 'høyre', index: 3, type: 'tå' },
        { side: 'høyre', index: 4, type: 'tå' },
    ],
}