var model = {
    names: ['lille', 'ring', 'midt', 'peke', ['tommel', 'storetå']],
    fingersAndToes: [
        { isLeftSide: true, index: 0, type: 0 },
        { isLeftSide: true, index: 1, type: 0 },
        { isLeftSide: true, index: 2, type: 0 },
        { isLeftSide: true, index: 3, type: 0 },
        { isLeftSide: true, index: 4, type: 0 },
        { isLeftSide: false, index: 0, type: 0 },
        { isLeftSide: false, index: 1, type: 0 },
        { isLeftSide: false, index: 2, type: 0 },
        { isLeftSide: false, index: 3, type: 0 },
        { isLeftSide: false, index: 4, type: 0 },
        { isLeftSide: true, index: 0, type: 1 },
        { isLeftSide: true, index: 1, type: 1 },
        { isLeftSide: true, index: 2, type: 1 },
        { isLeftSide: true, index: 3, type: 1 },
        { isLeftSide: true, index: 4, type: 1 },
        { isLeftSide: false, index: 0, type: 1 },
        { isLeftSide: false, index: 1, type: 1 },
        { isLeftSide: false, index: 2, type: 1 },
        { isLeftSide: false, index: 3, type: 1 },
        { isLeftSide: false, index: 4, type: 1 },
    ],
};

// var model =
// {
//     names: ['lille', 'ring', 'midt', 'peke', ['tommel', 'storetå']],
//     fingersAndToes: [
//         { side: 'venstre', index: 0, type: 0 },
//         { side: 'venstre', index: 1, type: 0 },
//         { side: 'venstre', index: 2, type: 0 },
//         { side: 'venstre', index: 3, type: 0 },
//         { side: 'venstre', index: 4, type: 0 },
//         { side: 'høyre', index: 0, type: 0 },
//         { side: 'høyre', index: 1, type: 0 },
//         { side: 'høyre', index: 2, type: 0 },
//         { side: 'høyre', index: 3, type: 0 },
//         { side: 'høyre', index: 4, type: 0 },
//         { side: 'venstre', index: 0, type: 0 },
//         { side: 'venstre', index: 1, type: 0 },
//         { side: 'venstre', index: 2, type: 0 },
//         { side: 'venstre', index: 3, type: 0 },
//         { side: 'venstre', index: 4, type: 0 },
//         { side: 'høyre', index: 0, type: 0 },
//         { side: 'høyre', index: 1, type: 0 },
//         { side: 'høyre', index: 2, type: 0 },
//         { side: 'høyre', index: 3, type: 0 },
//         { side: 'høyre', index: 4, type: 0 },
//     ],
// }